import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import {
  SessionProvider,
  ClientProvider,
  ReactQueryProvider,
} from "@/components/providers/index";
import { cn } from "@/lib/utils";
import { ReduxProvider } from "@/components/providers/redux-provider";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/layout/app-sidebar";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next.js Keycloak Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", inter.variable)}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <ReduxProvider>
            <ReactQueryProvider>
              <ClientProvider>
                <SidebarProvider>
                  <AppSidebar />
                  <main>{children}</main>
                </SidebarProvider>
              </ClientProvider>
            </ReactQueryProvider>
          </ReduxProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
